### ISSUE TITLE
URI naming convertion?

### ISSUE THREAD

**Issue by sweatyc** [alexeymezenin/laravel-best-practices#27]
E.g.:
$router->get('/users/forgot_password', 'UserController@forgotPassword');
or
$router->get('/users/forgot-password', 'UserController@forgotPassword');
or
$router->get('/users/forgotPassword', 'UserController@forgotPassword');

there's no clue in [Resource Controllers doc](https://laravel.com/docs/master/controllers#resource-controllers), but I guess **forgot-password** seems to be the way to go.

**Comment by dios-oleg** [comment]
$router->get('/users/forgot-password', 'UserController@forgotPassword');

URL часто регистронезависимый

**Comment by anandiamy** [comment]
But why "named route" uses snake_case ? 

![image](https://user-images.githubusercontent.com/8675936/60864579-2ac1bf00-a24e-11e9-9930-c22b66c236e8.png)

**Comment by poncianodiego** [comment]
For named routes is something that is not exposed to the user, and I think we mainly want snake case there because is easier to copy/paste(?), URIs are and these seems to be easier to read for most users I think. Hyphens are the standard across the web for URIs.

Is a good point though might be easier to remember, in exchange of say not being able to double click to select and copy/paste it.

**Comment by dios-oleg** [comment]
@anandiamy

I see several reasons:
1. In a text editor, to select a whole phrase, you need to double-click the mouse. The phrase should be separated by the symbol "_", and not "-" (depending on the settings).
2. Most often use short names with one verb or noun.

**Comment by alexeymezenin** [comment]
@anandiamy URLs are not related to Laravel. Personally, I prefer to use `-`.

As for routes and similar Laravel related stuff, I prefer to use `_` for the reasons @poncianodiego and @dios-oleg were talking about. Some developers don't like it and currently, there is voting here https://github.com/alexeymezenin/laravel-best-practices/pull/24
